raw_data_path: "DATA/resampled-data.csv"

model:
  path: "artifacts/model.pkl" 
  params:
    n_estimators: 510
    min_samples_split: 18
    min_samples_leaf: 19
    max_depth: 5
    random_state: 42 

mlflow:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "customer_churn_prediction"


  
